### PR TITLE
Fix new_hire_views.py

### PR DESCRIPTION
**Pull request by helgio**
Fix filter for finding sequences that will not be triggered. It should be gte not lte

### CODE REVIEW

**Comment by helgio** [comment]
Hi 
I hope I am not misunderstanding this, but like I understand the code is behaving, without my alteration:

This is the scope you are getting:

---- past  --- Today ----- 1 day before ---- start date ----  1 day after
	                      xxxxxxxxxxxxxxxxxxxxxxxx

you want this:

---- past  --- Today ----- 1 day before ---- start date ----  1 day after
xxxxxxxxxxxx


Like I understand the test:
you are creating a task that will trigger 1 day before the starting day. The starting day is in 7 days, the task in the test will be triggered. But the test and the code are saying it will not.

Time in dates can be so confusing, I am getting a headache writing this :)

**Comment by GDay** [comment]
@helgio My apologies, you are absolutely right! The test case and the original code is incorrect. Your fix is great!

If it's not too much of a hassle, could you fix the test case? I will merge this once tests pass. 
If you can't, just let me know and I will fix it. 

Thanks a lot!

**Comment by helgio** [comment]
My pleasure, I will fix the test :)

**Review by GDay — APPROVED** [review]
LGTM! Thanks again!

**Pull request merged**
