### PR TITLE
Implemented Letsencrypt, env var and volume fixes

### PR DESCRIPTION
**Pull request by valuko**
Changes to get letsencrypt working and set the random env var to wok with the container

### CODE REVIEW

**Comment by jeff-99** [comment]
I tried setting up from this fork and Let's encrypt is working when you first disable the HTTPS server config when running certbot.
Finally when the cert is validated nginx runs and the application can be accessed. 

Then when I visit the application it tries to request some resources on `http://0.0.0.0:8000`. Instead of the provided base url. 
@GDay where should the base url be added in setting up the server to fix this ?

image

**Comment by GDay** [comment]
Hey @jeff-99, thanks for that! We might have to add that to the environment configs then. But that should be in `front/nuxt.conf.js`! Will take a look in a bit.

**Comment by GDay** [comment]
To be exact: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/front/nuxt.config.js#L86

**Comment by jeff-99** [comment]
> To be exact: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/front/nuxt.config.js#L86

Hardcoding the correct base url fixed the issue. All seems to be working fine, but adding Appointments or Sequences just refreshes the page. Any clue what could be causing this behaviour ?

**Comment by GDay** [comment]
Weird issue, I have made an issue for that here: #4 . I am looking into it. Let's keep this PR on topic.

**Comment by GDay** [comment]
I have removed the permanent SSL redirect from the nginx file and set up Django to take care of that. This way, certbot should be able to authenticate/renew a domain. 

There seems to be one issue left to be fixed, before I can merge this into master:
```
BIO_new_file("/etc/ssl/certs/dhparam-2048.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/certs/dhparam-2048.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
Also tried `dhparam.pem`, but it can't find that either. Will take another look at that tomorrow.

**Comment by valuko** [comment]
Can you check inside the `/certbot/dhparam` directory in the code to see if the file is placed there? Thats the path linked to the volume `/etc/ssl/certs`.

**Pull request merged**
